# wisc_server 默认的启动地址
server_addr: 127.0.0.1:7777
# 命令行历史存放文件
command_history: history.txt

# 存放数据文件的基础目录
data_dir: data
# 数据文件的后缀名
data_file_suffix: .wisc
# 数据文件的扩展名
data_file_extension: wisc

# wal 日志存储目录
wal_dir: log
# 数据文件的后缀名
log_file_suffix: .xlog
# 数据文件的扩展名
log_file_extension: xlog

#########LSM############
# lsm 所有层级目录,共7 层
level_dirs:
  - 0
  - 1
  - 2
  - 3
  - 4
  - 5
  - 6

# block size，默认 4kb
block_size: 4096
# 重启点间隔,默认间隔16 个key
# 重启点有两个作用：
# 1 因为key是顺序排序的，首先是进行前缀压缩
# 2 我们可以通过重启点 快速跳过一些 key
block_restart_interval: 16

