# 存放数据文件的基础目录
data_dir: data
# 数据文件的后缀名
data_file_suffix: .wisc
# 数据文件的扩展名
data_file_extension: wisc
# 数据文件最大容量，超出则创建新文件写入数据,单位 字节
# 注意，此值并不是完全精确匹配，目的在于将数据在时间序上分散在多个文件中
# 默认 1024 * 1024 = 1048576
file_max_size: 1048576

# 压缩阈值：此处的数字统计 已进行的