# wisc_server 默认的启动地址
server_addr: 127.0.0.1:7777
# 命令行历史存放文件
command_history: history.txt

# 存放数据文件的基础目录
data_dir: data
# 数据文件的后缀名
data_file_suffix: .wisc
# 数据文件的扩展名
data_file_extension: wisc

# wal 日志存储目录
wal_dir: log
# 数据文件的后缀名
log_file_suffix: .xlog
# 数据文件的扩展名
log_file_extension: xlog

#########LSM############
# lsm 所有层级目录,共7 层
level_dirs:
  - 0
  - 1
  - 2
  - 3
  - 4
  - 5
  - 6

# 第0 层的总sst 文件大小的阈值，1024，单位byte
level_0_max_size: 1024
# 层级总容量扩充因子，
# 也就是第一层的总容量大小是 ：level_0_max_size * 10，
# 第二层的总容量大小是 ：level_0_max_size * 10 * 10，依次类推
level_expansion_factor: 10


